export const buttonTypes = {
    NUMBER: 'number',
    OPERATOR: 'operator',
    FUNCTION: 'function',
    CONSTANT: 'constant',
    RESET: 'AC',
    PARANTHESIS_OPEN: '(',
    PARANTHESIS_CLOSE: ')',
    POINT: '.',
    ANSWER: 'Ans',
    UNDO: 'Undo',
    REDO: 'Redo',
}

export const operators = {
    PLUS: '+',
    MINUS: '-',
    MULTIPLY: 'x',
    DIVIDE: '÷',
    POWER: 'pow',
    MODULUS: '%',
}

const claculatorButtons = [
    {value: {name: 'sin'}, type: buttonTypes.FUNCTION, color: 'secondary'},
    {value: {name: 'ln'}, type: buttonTypes.FUNCTION, color: 'secondary'},
    {value: {name: '7'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: '8'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: '9'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: operators.DIVIDE}, type: buttonTypes.OPERATOR, color: 'secondary'},
    {value: {name: 'cos'}, type: buttonTypes.FUNCTION, color: 'secondary'},
    {value: {name: 'log'}, type: buttonTypes.FUNCTION, color: 'secondary'},
    {value: {name: '4'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: '5'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: '6'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: operators.MULTIPLY}, type: buttonTypes.OPERATOR, color: 'secondary'},
    {value: {name: 'tan'}, type: buttonTypes.FUNCTION, color: 'secondary'},
    {value: {name: 'π'}, type: buttonTypes.CONSTANT, color: 'secondary'},
    {value: {name: '1'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: '2'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: '3'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: operators.MINUS}, type: buttonTypes.OPERATOR, color: 'secondary'},
    {value: {name: operators.POWER}, type: buttonTypes.OPERATOR, color: 'secondary'},
    {value: {name: 'e'}, type: buttonTypes.CONSTANT, color: 'secondary'},
    {value: {name: '0'}, type: buttonTypes.NUMBER, color: 'light'},
    {value: {name: buttonTypes.POINT}, type: buttonTypes.POINT, color: 'light'},
    {value: {name: buttonTypes.RESET}, type: buttonTypes.RESET, color: 'primary'},
    {value: {name: operators.PLUS}, type: buttonTypes.OPERATOR, color: 'secondary'},
    {value: {name: buttonTypes.PARANTHESIS_OPEN}, type: buttonTypes.PARANTHESIS_OPEN, color: 'secondary'},
    {value: {name: buttonTypes.PARANTHESIS_CLOSE}, type: buttonTypes.PARANTHESIS_CLOSE, color: 'secondary'},
    {value: {name: buttonTypes.UNDO}, type: buttonTypes.UNDO, color: 'warning'},
    {value: {name: buttonTypes.REDO}, type: buttonTypes.REDO, color: 'warning'},
    {value: {name: buttonTypes.ANSWER}, type: buttonTypes.CONSTANT, color: 'primary'},
    {value: {name: operators.MODULUS}, type: buttonTypes.OPERATOR, color: 'secondary'},
]

export default claculatorButtons;
